#!/bin/bash
# Simple build script, potentially useful if building a GPL-redistributable
# version on a system *without* SPEC CPU2017.  See:
#
#     https://www.spec.org/cpu2017/Docs/licenses.html#GPLtarballs
#
# Note: if the benchmark uses "specpp", that is the freely-redistributable
#       preprocessor "filepp".   It is described at 
#         https://www.spec.org/cpu2017/Docs/utility.html#specpp  
#       and will need to be in your path.  You can find filepp sources as
#       modified by SPEC in redistributable_sources/modified/tools.src/harness-spec.tar.xz 
#---------------------------------------------------------------------------

/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o nabmd.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  nabmd.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o sff.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  sff.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o nblist.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  nblist.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o prm.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  prm.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o memutil.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  memutil.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o molio.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  molio.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o molutil.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  molutil.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o errormsg.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  errormsg.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o binpos.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  binpos.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o rand2.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  rand2.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o select_atoms.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  select_atoms.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o reslib.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  reslib.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o database.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  database.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o traceback.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  traceback.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o chirvol.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  chirvol.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o specrand/specrand.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  specrand/specrand.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o regex-alpha/regcomp.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  regex-alpha/regcomp.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o regex-alpha/regerror.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  regex-alpha/regerror.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o regex-alpha/regexec.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  regex-alpha/regexec.c
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize     -std=c99   -m64 -c -o regex-alpha/regfree.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE -DSPEC_AUTO_SUPPRESS_OPENMP                -DSPEC_LP64  regex-alpha/regfree.c
